/*
 * Build the shared Queens campaign. Generates a fixed set of puzzles from a
 * seeded RNG and writes js/puzzles.js. Run once and commit the output — the
 * committed file IS the campaign: identical for every player, frozen against
 * future engine changes.
 *
 *   node scripts/generate-queens.js [count]   (default 500)
 *
 * Sizes are mixed 7..11 (balanced) and shuffled, so difficulty varies level to
 * level with no ramp.
 */
'use strict';

const fs = require('fs');
const path = require('path');
const engine = require('../js/queens-engine.js');

const COUNT = parseInt(process.argv[2] || '500', 10);
const SEED = 0x51ee2;
const OUT = path.join(__dirname, '..', 'js', 'puzzles.js');

function mulberry32(seed) {
  let a = seed >>> 0;
  return function () {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function shuffle(arr, rng) {
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(rng() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
  return arr;
}

const rng = mulberry32(SEED);

// Balanced, shuffled mix of sizes 7..11.
const sizes = [];
for (let i = 0; i < COUNT; i++) sizes.push(7 + (i % 5));
shuffle(sizes, rng);

const puzzles = [];
const seen = new Set();
const t0 = Date.now ? null : null; // Date.now unavailable in some sandboxes; timing via process.hrtime below
const start = process.hrtime.bigint();

for (let i = 0; i < COUNT; i++) {
  const N = sizes[i];
  let p, key;
  do {
    p = engine.generatePuzzle(rng, N);
    key = N + ':' + p.grid.map((row) => row.join('')).join('|');
  } while (seen.has(key));
  seen.add(key);
  puzzles.push(p);
  if ((i + 1) % 50 === 0) {
    const secs = Number(process.hrtime.bigint() - start) / 1e9;
    console.log(`  ${i + 1}/${COUNT} (${secs.toFixed(1)}s)`);
  }
}

const lines = puzzles
  .map((p) => '  ' + JSON.stringify({ size: p.size, grid: p.grid, solution: p.solution }))
  .join(',\n');

const file =
  '/* Shared Queens campaign — generated by scripts/generate-queens.js. Do not edit by hand. */\n' +
  'window.QUEENS_PUZZLES = [\n' + lines + '\n];\n';

fs.writeFileSync(OUT, file);

const counts = {};
for (const p of puzzles) counts[p.size] = (counts[p.size] || 0) + 1;
const totalSecs = Number(process.hrtime.bigint() - start) / 1e9;
console.log(`Wrote ${puzzles.length} puzzles to ${path.relative(process.cwd(), OUT)} (${(file.length / 1024).toFixed(0)} KB) in ${totalSecs.toFixed(1)}s.`);
console.log('Size distribution:', counts);
